version: '3.8'

services:
  nextjs-build:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: sh -c "yarn install && yarn build && yarn start"
    ports:
      - '3000:3000'